import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 18

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "transparent"
opacity = 0.88

[window.padding]
x = 5
y = 30

[env]
TERM = "xterm-256color"
